apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apiz-backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dummy-plugin
  description: Fake REST API of JSON data
  # Example for optional annotations
  annotations:
    backstage.io/managed-by-location: url:https://github.com/GregHry/apiz-backstage/blob/main/catalog-info.yaml
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: ghe@contraste.com
  lifecycle: experimental

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-actions
  description: CI/CD github actions
  annotations:
    github.com/project-slug: GregHry/apiz-backstage
spec:
  type: service
  lifecycle: production
  owner: Greg

---

apiVersion:  backstage.io/v1alpha1
kind: Component
metadata:
  name: BackstageApp
  description: Backstageception
  annotations:
    backstage.io/managed-by-location: https://github.com/GregHry/apiz-backstage/blob/main/catalog-info.yaml
    github.com/project-slug: GregHry/apiz-backstage
    backstage.io/techdocs-ref: dir:.
  tags:
    - web
spec:
  type: service
  lifecycle: experimental
  owner: Greg